### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sangemeng** [lrqtech/smya-go#3]
```
Connect lost: pingresp not received, disconnecting
Try to restart program
Connect success !
Get https://time.hl98.cn: read tcp 192.168.0.188:35392->47.115.178.15:443: read: connection timed out
Get https://time.hl98.cn: read tcp 192.168.0.188:35392->47.115.178.15:443: read: connection timed out
Get https://time.hl98.cn: read tcp 192.168.0.188:35392->47.115.178.15:443: read: connection timed out
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x23df68]

goroutine 2110 [running]:
smya/util.Request(0x3443ac, 0x3, 0x349580, 0x14, 0x5ffa30, 0x0, 0x0, 0x200, 0x0, 0x0, ...)
        /www/wwwroot/0.0.0.0/data/User/admin/home/myapps/smya-go/util/http.go:29 +0x278
smya/mytime.GetTime(0x0, 0x4000037710)
        /www/wwwroot/0.0.0.0/data/User/admin/home/myapps/smya-go/mytime/time.go:13 +0x60
smya/mytime.SetHour()
        /www/wwwroot/0.0.0.0/data/User/admin/home/myapps/smya-go/mytime/time.go:21 +0x20
github.com/robfig/cron/v3.FuncJob.Run(0x35ef98)
        /root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x28
github.com/robfig/cron/v3.(*Cron).startJob.func1(0x40000fa000, 0x3bc220, 0x35ef98)
        /root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x68
created by github.com/robfig/cron/v3.(*Cron).startJob
        /root/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0x68

```
大佬运行时间长了，程序崩了。

**Comment by lrqtech** [comment]
已经修复
